// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7jG-1c3rRq6l0CK9Fyyb_RFCDVjSeJo',
    appId: '1:159574153331:web:5bc68ffd1b4e9def67b206',
    messagingSenderId: '159574153331',
    projectId: 'testapp-b16f6',
    authDomain: 'testapp-b16f6.firebaseapp.com',
    storageBucket: 'testapp-b16f6.appspot.com',
    measurementId: 'G-9HJ9QJ4C6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5pUQVSb10fYTjz_nzLrJTNyKslQBzVao',
    appId: '1:159574153331:android:1e9d563eab3727ef67b206',
    messagingSenderId: '159574153331',
    projectId: 'testapp-b16f6',
    storageBucket: 'testapp-b16f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNhYHZybzLB5KC3tjHE1P3D-MZTM__Zco',
    appId: '1:159574153331:ios:aa428b15bd286fc267b206',
    messagingSenderId: '159574153331',
    projectId: 'testapp-b16f6',
    storageBucket: 'testapp-b16f6.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNhYHZybzLB5KC3tjHE1P3D-MZTM__Zco',
    appId: '1:159574153331:ios:aa428b15bd286fc267b206',
    messagingSenderId: '159574153331',
    projectId: 'testapp-b16f6',
    storageBucket: 'testapp-b16f6.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu7jG-1c3rRq6l0CK9Fyyb_RFCDVjSeJo',
    appId: '1:159574153331:web:504c22ee2c408de567b206',
    messagingSenderId: '159574153331',
    projectId: 'testapp-b16f6',
    authDomain: 'testapp-b16f6.firebaseapp.com',
    storageBucket: 'testapp-b16f6.appspot.com',
    measurementId: 'G-PJJLZRGX49',
  );
}
